const PptxGenJS = require("pptxgenjs");
const path = require('path');
const fs = require('fs');

class PptGenerator {
  static async generate(resultData, fileName, companyName) {
    try {
      // Pastikan folder reports ada
      const reportsDir = path.join(__dirname, '..', 'reports');
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }
      
      const pptx = new PptxGenJS();
      
      // === SLIDE 1: COVER ===
      const slide1 = pptx.addSlide();
      slide1.background = { fill: "1F4E79" };
      slide1.addText("HASIL MARKET BASKET ANALYSIS", {
        x: 0.5, y: 1.5, w: 9, h: 1.5,
        fontSize: 32, bold: true, color: "FFFFFF",
        align: "center"
      });
      slide1.addText(companyName || "Laporan Bisnis", {
        x: 0.5, y: 3, w: 9, h: 1,
        fontSize: 20, color: "FFFFFF", align: "center"
      });
      slide1.addText(new Date().toLocaleDateString('id-ID'), {
        x: 0.5, y: 4, w: 9, h: 0.5,
        fontSize: 14, color: "FFFFFF", align: "center"
      });
      
      // === SLIDE 2: RINGKASAN ===
      const slide2 = pptx.addSlide();
      slide2.addText("Ringkasan Eksekutif", {
        x: 0.5, y: 0.5, w: 9, h: 1,
        fontSize: 24, bold: true, color: "1F4E79"
      });
      
      const summaryData = [
        [{ text: "Metrik", options: { bold: true, color: "FFFFFF", fill: { color: "1F4E79" } } },
         { text: "Nilai", options: { bold: true, color: "FFFFFF", fill: { color: "1F4E79" } } }],
        ["Total Transaksi", `${resultData.totalTransactions}`],
        ["Total Rules Ditemukan", `${resultData.totalRules}`],
        ["Minimum Support", `${(resultData.parameters.minSupport * 100)}%`],
        ["Minimum Confidence", `${(resultData.parameters.minConfidence * 100)}%`]
      ];
      
      slide2.addTable(summaryData, {
        x: 1, y: 1.5, w: 8,
        border: { type: "solid", pt: 1, color: "CCCCCC" }
      });
      
      // === SLIDE 3: TOP 10 RULES ===
      const slide3 = pptx.addSlide();
      slide3.addText("Top 10 Association Rules", {
        x: 0.5, y: 0.5, w: 9, h: 1,
        fontSize: 24, bold: true, color: "1F4E79"
      });
      
      const top10 = resultData.rules.slice(0, 10);
      const tableData = [
        [{ text: "Aturan", options: { bold: true, fill: { color: "1F4E79" }, color: "FFFFFF" } },
         { text: "Support", options: { bold: true, fill: { color: "1F4E79" }, color: "FFFFFF" } },
         { text: "Confidence", options: { bold: true, fill: { color: "1F4E79" }, color: "FFFFFF" } },
         { text: "Lift", options: { bold: true, fill: { color: "1F4E79" }, color: "FFFFFF" } }],
        ...top10.map(rule => [
          `${rule.antecedent} → ${rule.consequent}`,
          `${(rule.support * 100).toFixed(1)}%`,
          `${(rule.confidence * 100).toFixed(1)}%`,
          rule.lift.toFixed(2)
        ])
      ];
      
      slide3.addTable(tableData, {
        x: 0.3, y: 1.5, w: 9.4,
        border: { type: "solid", pt: 1, color: "CCCCCC" },
        colW: [4.5, 1.7, 1.7, 1.5]
      });
      
      // === SLIDE 4: INSIGHT BISNIS ===
      const slide4 = pptx.addSlide();
      slide4.addText("Insight & Rekomendasi Bisnis", {
        x: 0.5, y: 0.5, w: 9, h: 1,
        fontSize: 24, bold: true, color: "1F4E79"
      });
      
      const topRules = resultData.rules.slice(0, 5);
      topRules.forEach((rule, index) => {
        slide4.addText(`${index + 1}. ${rule.description}`, {
          x: 1, y: 1.5 + (index * 0.7), w: 8, h: 0.6,
          fontSize: 13, color: "333333"
        });
      });
      
      slide4.addText("💡 Rekomendasi:", {
        x: 1, y: 5.5, w: 8, h: 0.5,
        fontSize: 16, bold: true, color: "C0392B"
      });
      
      const recommendations = [
        "Buat paket bundle produk yang sering dibeli bersamaan",
        "Letakkan produk complementary berdekatan di toko",
        "Gunakan rules untuk cross-selling di kasir"
      ];
      
      recommendations.forEach((rec, index) => {
        slide4.addText(`• ${rec}`, {
          x: 1.2, y: 6 + (index * 0.4), w: 7.6, h: 0.4,
          fontSize: 12, color: "333333"
        });
      });
      
      // === SLIDE 5: PENUTUP ===
      const slide5 = pptx.addSlide();
      slide5.background = { fill: "1F4E79" };
      slide5.addText("Terima Kasih", {
        x: 0.5, y: 2.5, w: 9, h: 1.5,
        fontSize: 36, bold: true, color: "FFFFFF", align: "center"
      });
      slide5.addText("Generated by Market Basket Analysis System", {
        x: 0.5, y: 4, w: 9, h: 0.5,
        fontSize: 14, color: "FFFFFF", align: "center"
      });
      
      // Simpan file
      const safeFileName = fileName.replace(/[^a-zA-Z0-9]/g, '_');
      const outputPath = path.join(reportsDir, `${Date.now()}-${safeFileName}.pptx`);
      await pptx.writeFile({ fileName: outputPath });
      
      return outputPath;
    } catch (error) {
      throw new Error(`Gagal generate PPT: ${error.message}`);
    }
  }
}

module.exports = PptGenerator;
